### ISSUE TITLE
Stops parsing when it encounters a pound sign £

### ISSUE THREAD

**Issue by ashleyhindle** [jemmyw/Qif#14]
When you have something like this:

```
PCARD PAYMENT TO LINODE.COM,35.00 USD, RATE 0.65/£ ON 01-05-2015 (INTERNATIONAL USE FEE £0., 23.63
```

It can't parse it and stops at it, rather than skipping it and continuing, or throwing an error.

If I remove the £ signs, it works fine

**Comment by jemmyw** [comment]
I've not been able to replicate this with the latest version of the gem or ruby. It sounds like it might be an encoding issue of some kind. If you come across the issue still please send an example broken qif file and specify the version of ruby used.
